# Site settings
title: Techtábor - A Gondolkodás Öröme Alapítvány
email:
description: A Techtábor honlapja - projektek és metodológia

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://techtabor.github.io" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
#data-ad-slot: 2973388149
#data-ad-client: ca-pub-9204963049240271
#google_ad_client: ca-pub-9204963049240271

#google_analytics: "UA-86331249-1"
#addthis_id: ra-5644da281510c62f
#disqus_account: jeky-new-age

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
# Other available: twitter, facebook, google-plus, github
social:
  #- title: twitter
  #  url: https://twitter.com/lantoniotrento
  - title: facebook
    url: https://facebook.com/agondolkodasorome
  #- title: google-plus
  #  url: https://plus.google.com/+AntoniotrentoIt
  - title: github
    url: http://github.com/techtabor

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 100
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
